version: '2'
services:
  relay-ws-server:
    image: docker.kumay.net/relay-ws-server:latest
    restart: always
    env_file:
      - .env
    networks:
      - websocket
networks:
  websocket:
    external: true